### ISSUE TITLE
No License Information

### ISSUE THREAD

**Issue by ktsashes** [TGOlson/dupertest#7]
There isn't any license information in the repo. From the package.json file, it looks like you intend it to be MIT, but there is no LICENSE file. If MIT is correct, would you mind adding one?

**Comment by TGOlson** [comment]
Hey @ktsashes, thanks for the heads up. Release [1.0.2](https://github.com/TGOlson/dupertest/releases/tag/v1.0.2) adds a license file. Hopefully that takes care of what you need.

**Comment by ktsashes** [comment]
Thanks :)
